275 lunch ticket qr code
careerfairsystems/nexpo-app pull request #289
Opened 2023-04-23 09:43 UTC by emil-ronkainen

For any admin, volunteer or student, there is now a button on the profile page for displaying their lunch ticket as a qr code.

Closes #275.

## Checklist
- [x] Have you remembered to run the `test_actions.sh` script?
- [x] Have you rebased the branch on the latest main?
- [x] Have you tested the change locally?

2023-04-23 20:21 UTC, Stronkness commented
Note that students shouldn't see lunch or banquett tickets in the app as they are not a part of ARKAD. This need to be fixed.
For now only admins and volounteers should see the ticket, but company representative can be included also as this will be IT 24s job

2023-04-23 20:23 UTC, Stronkness commented on screens/profile/ProfileScreen.tsx
> +          { !company && (
!student right?

2023-04-23 20:25 UTC, Stronkness requested changes
Change to !student

2023-04-24 18:50 UTC, emil-ronkainen reviewed
Updated conditional rendering of ShowLunchTicketButton. Now displays for every user but the student role

2023-04-24 19:38 UTC, emil-ronkainen commented
After some testing it seems that this issue might already be resolved. Due to the lunch tickets using the same "pipeline" as any other event, it is already displayed on the profile page and can be clicked to open a view with further information and the qr code. Attatching an image of the situation below (running on branch "mockDataForTicketAndEVEnt" on backend and logged in as user "student1@example.com")

I am marking the PR as draft until this is addressed.

<img width="481" alt="image" src="https://user-images.githubusercontent.com/47136996/234098098-48cd20dc-3444-450c-a230-9a897c8e4c95.png">

2023-04-27 14:38 UTC, Stronkness commented
Honestly i think this looks great, i think we should stick with the pipeline event. Fix the merge conflict and we good to go

2023-04-27 15:36 UTC, emil-ronkainen commented
Closing this as the feature is already implemented

2023-04-27 15:36 UTC, closed without merging